
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.7"
  install:
  - requirements: requirements/runtime.txt
  - requirements: requirements/docs.txt
  - method: setuptools
    path: .
