#!/bin/bash
echo "AcccessKey checking ...."
projectUrl=`git config --get remote.origin.url`
user=`git config --get user.name`
user_email=`git config --get user.email`
STAGE_FILES=$(git diff --cached --name-only)
stage_files=(${STAGE_FILES/ // })
keywords=("LTAI[a-zA-Z0-9]{20}" "LTAI[a-zA-Z0-9]{12}")

result=0
for i in "${!stage_files[@]}"; do
    if [ ! -e "${stage_files[i]}" ]
    then
      continue
    fi
    for index in "${!keywords[@]}"; do
      grep -E -q ${keywords[index]} ${stage_files[i]}
      if [ $? -eq 0 ] 
      then
         echo "Check Failed,  ${stage_files[i]} containes AcccessKey. ${keywords[index]}"
         grep -E ${keywords[index]} ${stage_files[i]}
         result=1
         break
      fi
    done
done
if [ $result -eq 0 ];then
  echo "Check Successed"
else 
  exit 1
fi
data="{\"projectUrl\":\"${projectUrl}\",\"committer\":\"${user}\",\"status\":${result},\"committerEmail\":\"${user_email}\"}"
curl -H "Content-type: application/json" -X POST -d"$data" 'https://blinktestplat.alibaba-inc.com/githubcheck/api/updateGitCheck'
