# -*- encoding:utf-8 -*-
# Copyright (c) Alibaba, Inc. and its affiliates.

SAMPLE_WEIGHT = 'SAMPLE_WEIGHT'

DENSE_UPDATE_VARIABLES = 'DENSE_UPDATE_VARIABLES'

SPARSE_UPDATE_VARIABLES = 'SPARSE_UPDATE_VARIABLES'
