# -*- encoding:utf-8 -*-
# Copyright (c) Alibaba, Inc. and its affiliates.

SAMPLE_WEIGHT = 'SAMPLE_WEIGHT'

DENSE_TRAIN_VARIABLES = 'DENSE_TRAIN_VARIABLES'

SPARSE_TRAIN_VARIABLES = 'SPARSE_TRAIN_VARIABLES'
